const $=(id)=>document.getElementById(id);let tabId=null,selectedMode="balanced";
const PRESETS={stable:{scanMs:500,refreshSeconds:10},balanced:{scanMs:200,refreshSeconds:3},sprint:{scanMs:100,refreshSeconds:1}};
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.url?.startsWith("https://bigmodel.cn/glm-coding"))throw new Error("请先打开 GLM Coding 页面");return tab;}
function formSettings(){return{mode:selectedMode,scanMs:Number($("scanMs").value),autoRefresh:$("autoRefresh").checked,refreshSeconds:Number($("refresh").value),soundEnabled:$("sound").checked,notificationsEnabled:$("notifications").checked};}
function render({settings,run,logs}){selectedMode=settings.mode;$("scanMs").value=settings.scanMs;$("autoRefresh").checked=settings.autoRefresh;$("refresh").value=settings.refreshSeconds;$("refresh").disabled=!settings.autoRefresh;$("sound").checked=settings.soundEnabled;$("notifications").checked=settings.notificationsEnabled;$("status").textContent=run?.status??"未开始";$("dot").classList.toggle("active",Boolean(run?.active));$("checks").textContent=run?.checks??0;$("next").textContent=run?.nextRefreshAt?`${Math.max(0,Math.ceil((run.nextRefreshAt-Date.now())/1000))}s`:"—";$("reason").textContent=run?.backoffReason??"—";document.querySelectorAll("[data-mode]").forEach((b)=>b.classList.toggle("active",b.dataset.mode===selectedMode));$("logs").replaceChildren(...(logs??[]).slice(-30).reverse().map((e)=>{const row=document.createElement("div");row.textContent=`${e.at} ${e.message}`;return row;}));}
async function save(){const result=await chrome.runtime.sendMessage({type:"UPDATE_SETTINGS",settings:formSettings()});return result.settings;}async function refresh(){render(await chrome.runtime.sendMessage({type:"GET_STATE",tabId}));}
document.addEventListener("DOMContentLoaded",async()=>{try{tabId=(await activeTab()).id;await refresh();}catch(error){$("status").textContent=error.message;$("start").disabled=true;}});
$("autoRefresh").addEventListener("change",async()=>{$("refresh").disabled=!$("autoRefresh").checked;await save();});$("start").addEventListener("click",async()=>{await save();await chrome.runtime.sendMessage({type:"START_MONITORING",tabId});await refresh();});$("stop").addEventListener("click",async()=>{await chrome.runtime.sendMessage({type:"STOP_MONITORING",tabId});await refresh();});
document.querySelectorAll("[data-mode]").forEach((b)=>b.addEventListener("click",async()=>{selectedMode=b.dataset.mode;const p=PRESETS[selectedMode];if(p){$("scanMs").value=p.scanMs;$("refresh").value=p.refreshSeconds;}await save();await refresh();}));for(const id of["scanMs","refresh","sound","notifications"])$(id).addEventListener("change",async()=>{selectedMode="custom";await save();});
