const $=(id)=>document.getElementById(id);let tabId=null,selectedMode="balanced",planPriority=[],discoveredPlans=[],periodFilter="all";
const PRESETS={stable:{scanMs:500,refreshSeconds:10},balanced:{scanMs:200,refreshSeconds:3},sprint:{scanMs:100,refreshSeconds:1}},periodName={monthly:"月付",quarterly:"季付",annual:"年付"},key=(p)=>`${p.name}|${p.billingPeriod}|${p.price}`;
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.url?.startsWith("https://bigmodel.cn/glm-coding"))throw new Error("请先打开 GLM Coding 页面");return tab;}
function formSettings(){return{mode:selectedMode,scanMs:Number($("scanMs").value),autoRefresh:$("autoRefresh").checked,refreshSeconds:Number($("refresh").value),soundEnabled:$("sound").checked,notificationsEnabled:$("notifications").checked,planPriority};}
async function save(){return(await chrome.runtime.sendMessage({type:"UPDATE_SETTINGS",settings:formSettings()})).settings;}
function planRow(p){const row=document.createElement("label");row.className="plan-row";const box=document.createElement("input");box.type="checkbox";box.checked=planPriority.some((x)=>key(x)===key(p));box.onchange=async()=>{if(box.checked&&!planPriority.some((x)=>key(x)===key(p)))planPriority.push({fingerprint:key(p),name:p.name,price:p.price,billingPeriod:p.billingPeriod});if(!box.checked)planPriority=planPriority.filter((x)=>key(x)!==key(p));await save();renderPlans();};const name=document.createElement("strong");name.textContent=p.name;const period=document.createElement("span");period.className="period";period.textContent=periodName[p.billingPeriod]??p.billingPeriod;const price=document.createElement("span");price.className="price";price.textContent=p.price||"—";const state=document.createElement("span");state.className=`state ${p.eligible?"ok":"off"}`;state.textContent=p.eligible?"可用":"不可用";row.append(box,name,period,price,state);return row;}
function priorityRow(p,i){const row=document.createElement("div");row.className="priority-row";const rank=document.createElement("span");rank.className="rank";rank.textContent=i+1;const text=document.createElement("div");text.innerHTML=`<strong>${p.name}</strong><br><small>${periodName[p.billingPeriod]??"未知周期"} · ${p.price}</small>`;const actions=document.createElement("div");actions.className="row-actions";for(const [label,title,d]of[["↑","上移",-1],["↓","下移",1]]){const b=document.createElement("button");b.textContent=label;b.title=title;b.disabled=i+d<0||i+d>=planPriority.length;b.onclick=async()=>{[planPriority[i],planPriority[i+d]]=[planPriority[i+d],planPriority[i]];await save();renderPlans();};actions.append(b);}const del=document.createElement("button");del.textContent="×";del.title="移除";del.onclick=async()=>{planPriority.splice(i,1);await save();renderPlans();};actions.append(del);row.append(rank,text,actions);return row;}
function renderPlans(){const visible=discoveredPlans.filter((p)=>periodFilter==="all"||p.billingPeriod===periodFilter);$("planList").replaceChildren(...(visible.length?visible.map(planRow):[Object.assign(document.createElement("div"),{className:"empty",textContent:discoveredPlans.length?"该周期暂无方案":"尚未读取页面套餐"})]));$("priority").replaceChildren(...(planPriority.length?planPriority.map(priorityRow):[Object.assign(document.createElement("div"),{className:"empty",textContent:"尚未选择目标套餐"})]));$("planWarning").hidden=planPriority.length>0;}
function render({settings,run,logs}){selectedMode=settings.mode;planPriority=settings.planPriority??[];$("scanMs").value=settings.scanMs;$("autoRefresh").checked=settings.autoRefresh;$("refresh").value=settings.refreshSeconds;$("refresh").disabled=!settings.autoRefresh;$("sound").checked=settings.soundEnabled;$("notifications").checked=settings.notificationsEnabled;$("status").textContent=run?.status??"未开始";$("dot").classList.toggle("active",Boolean(run?.active));$("checks").textContent=run?.checks??0;$("next").textContent=run?.nextRefreshAt?`${Math.max(0,Math.ceil((run.nextRefreshAt-Date.now())/1000))}s`:"—";$("reason").textContent=run?.backoffReason??"—";document.querySelectorAll("[data-mode]").forEach((b)=>b.classList.toggle("active",b.dataset.mode===selectedMode));renderPlans();$("logs").replaceChildren(...(logs??[]).slice(-30).reverse().map((e)=>{const row=document.createElement("div");row.textContent=`${e.at} ${e.message}`;return row;}));}
async function refresh(){render(await chrome.runtime.sendMessage({type:"GET_STATE",tabId}));}
function renderRuntime({run,logs}){$("status").textContent=run?.status??"未开始";$("dot").classList.toggle("active",Boolean(run?.active));$("checks").textContent=run?.checks??0;$("next").textContent=run?.nextRefreshAt?`${Math.max(0,Math.ceil((run.nextRefreshAt-Date.now())/1000))}s`:"—";$("reason").textContent=run?.backoffReason??"—";const running=Boolean(run?.active);$("start").disabled=running;$("start").textContent=running?"监测运行中":"▶ 开始监测";$("logs").replaceChildren(...(logs??[]).slice(-30).reverse().map((e)=>{const row=document.createElement("div");row.textContent=`${e.at} ${e.message}`;return row;}));}
async function refreshRuntime(){renderRuntime(await chrome.runtime.sendMessage({type:"GET_STATE",tabId}));}
document.addEventListener("DOMContentLoaded",async()=>{try{tabId=(await activeTab()).id;await refresh();}catch(e){$("status").textContent=e.message;$("start").disabled=true;}});
$("discover").onclick=async()=>{$("discover").disabled=true;$("scanProgress").textContent="正在依次读取月付、季付、年付…";const result=await chrome.runtime.sendMessage({type:"DISCOVER_PLANS",tabId});discoveredPlans=result?.plans??[];$("scanErrors").hidden=!(result?.errors?.length);$("scanErrors").textContent=result?.errors?.join("；")??"";$("scanProgress").textContent=`已读取 ${discoveredPlans.length} 个套餐变体`;$("discover").disabled=false;renderPlans();};
document.querySelectorAll("[data-period]").forEach((b)=>b.onclick=()=>{periodFilter=b.dataset.period;document.querySelectorAll("[data-period]").forEach((x)=>x.classList.toggle("active",x===b));renderPlans();});$("autoRefresh").onchange=async()=>{$("refresh").disabled=!$("autoRefresh").checked;await save();};$("start").onclick=async()=>{await save();const r=await chrome.runtime.sendMessage({type:"START_MONITORING",tabId});if(!r.ok)$("status").textContent=r.error;else await refresh();};$("stop").onclick=async()=>{await chrome.runtime.sendMessage({type:"STOP_MONITORING",tabId});await refresh();};document.querySelectorAll("[data-mode]").forEach((b)=>b.onclick=async()=>{selectedMode=b.dataset.mode;const p=PRESETS[selectedMode];if(p){$("scanMs").value=p.scanMs;$("refresh").value=p.refreshSeconds;}await save();await refresh();});for(const id of["scanMs","refresh","sound","notifications"])$(id).onchange=async()=>{selectedMode="custom";await save();};
setInterval(()=>{if(tabId)refreshRuntime().catch(()=>{});},500);
