const $=(id)=>document.getElementById(id);let tabId=null,selectedMode="balanced",planPriority=[],discoveredPlans=[];
const PRESETS={stable:{scanMs:500,refreshSeconds:10},balanced:{scanMs:200,refreshSeconds:3},sprint:{scanMs:100,refreshSeconds:1}},key=(p)=>`${p.name}|${p.price}`;
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.url?.startsWith("https://bigmodel.cn/glm-coding"))throw new Error("请先打开 GLM Coding 页面");return tab;}
function formSettings(){return{mode:selectedMode,scanMs:Number($("scanMs").value),autoRefresh:$("autoRefresh").checked,refreshSeconds:Number($("refresh").value),soundEnabled:$("sound").checked,notificationsEnabled:$("notifications").checked,planPriority};}
async function save(){return(await chrome.runtime.sendMessage({type:"UPDATE_SETTINGS",settings:formSettings()})).settings;}
function renderPlans(){$("planList").replaceChildren(...discoveredPlans.map((p)=>{const row=document.createElement("label"),box=document.createElement("input");box.type="checkbox";box.checked=planPriority.some((x)=>key(x)===key(p));box.onchange=async()=>{if(box.checked&&!planPriority.some((x)=>key(x)===key(p)))planPriority.push({fingerprint:key(p),name:p.name,price:p.price});if(!box.checked)planPriority=planPriority.filter((x)=>key(x)!==key(p));await save();renderPlans();};row.append(box,document.createTextNode(` ${p.name} · ${p.price||"未识别价格"} · ${p.eligible?"可购买":"不可用"}`));return row;}));$("priority").replaceChildren(...planPriority.map((p,i)=>{const row=document.createElement("div");row.append(document.createTextNode(`${i+1}. ${p.name} ${p.price} `));for(const [label,d]of[["上移",-1],["下移",1]]){const b=document.createElement("button");b.textContent=label;b.disabled=i+d<0||i+d>=planPriority.length;b.onclick=async()=>{[planPriority[i],planPriority[i+d]]=[planPriority[i+d],planPriority[i]];await save();renderPlans();};row.append(b);}const del=document.createElement("button");del.textContent="移除";del.onclick=async()=>{planPriority.splice(i,1);await save();renderPlans();};row.append(del);return row;}));$("planWarning").hidden=planPriority.length>0;}
function render({settings,run,logs}){selectedMode=settings.mode;planPriority=settings.planPriority??[];$("scanMs").value=settings.scanMs;$("autoRefresh").checked=settings.autoRefresh;$("refresh").value=settings.refreshSeconds;$("refresh").disabled=!settings.autoRefresh;$("sound").checked=settings.soundEnabled;$("notifications").checked=settings.notificationsEnabled;$("status").textContent=run?.status??"未开始";$("dot").classList.toggle("active",Boolean(run?.active));$("checks").textContent=run?.checks??0;$("next").textContent=run?.nextRefreshAt?`${Math.max(0,Math.ceil((run.nextRefreshAt-Date.now())/1000))}s`:"—";$("reason").textContent=run?.backoffReason??"—";document.querySelectorAll("[data-mode]").forEach((b)=>b.classList.toggle("active",b.dataset.mode===selectedMode));renderPlans();$("logs").replaceChildren(...(logs??[]).slice(-30).reverse().map((e)=>{const row=document.createElement("div");row.textContent=`${e.at} ${e.message}`;return row;}));}
async function refresh(){render(await chrome.runtime.sendMessage({type:"GET_STATE",tabId}));}
document.addEventListener("DOMContentLoaded",async()=>{try{tabId=(await activeTab()).id;await refresh();}catch(e){$("status").textContent=e.message;$("start").disabled=true;}});
$("discover").onclick=async()=>{discoveredPlans=(await chrome.runtime.sendMessage({type:"DISCOVER_PLANS",tabId}))?.plans??[];renderPlans();};$("autoRefresh").onchange=async()=>{$("refresh").disabled=!$("autoRefresh").checked;await save();};$("start").onclick=async()=>{await save();const r=await chrome.runtime.sendMessage({type:"START_MONITORING",tabId});if(!r.ok)$("status").textContent=r.error;else await refresh();};$("stop").onclick=async()=>{await chrome.runtime.sendMessage({type:"STOP_MONITORING",tabId});await refresh();};
document.querySelectorAll("[data-mode]").forEach((b)=>b.onclick=async()=>{selectedMode=b.dataset.mode;const p=PRESETS[selectedMode];if(p){$("scanMs").value=p.scanMs;$("refresh").value=p.refreshSeconds;}await save();await refresh();});for(const id of["scanMs","refresh","sound","notifications"])$(id).onchange=async()=>{selectedMode="custom";await save();};
